import type { Vocabulary, Lesson, Grammar, Example, Kanji } from '@/lib/types';
import { Level, WordType } from '@/lib/types';

// ============================================
// USER DATA
// ============================================
const users = [
	{
		id: 'user-001',
		email: 'tanaka@example.com',
		name: 'Tanaka Yuki',
		username: 'tanaka_yuki',
		password: '$2b$10$hashed_password_here', // hashed password
		createdAt: new Date('2024-01-15'),
		updatedAt: new Date('2024-01-15'),
	},
	{
		id: 'user-002',
		email: 'nguyen@example.com',
		name: 'Nguyen Van A',
		username: 'nguyen_van_a',
		password: '$2b$10$hashed_password_here',
		createdAt: new Date('2024-02-20'),
		updatedAt: new Date('2024-02-20'),
	},
];

// ============================================
// LESSON DATA
// ============================================
export const lessons: Lesson[] = [
	{
		id: 'lesson-001',
		lessonNumber: 1,
		source: 'minna no nihongo',
		level: Level.N5,
	},
	{
		id: 'lesson-002',
		lessonNumber: 2,
		source: 'minna no nihongo',
		level: Level.N5,
	},
	{
		id: 'lesson-001',
		lessonNumber: 3,
		source: 'minna no nihongo',
		level: Level.N5,
	},
	{
		id: 'lesson-002',
		lessonNumber: 4,
		source: 'minna no nihongo',
		level: Level.N5,
	},
	{
		id: 'lesson-001',
		lessonNumber: 5,
		source: 'minna no nihongo',
		level: Level.N5,
	},
	{
		id: 'lesson-002',
		lessonNumber: 6,
		source: 'minna no nihongo',
		level: Level.N5,
	},
	{
		id: 'lesson-001',
		lessonNumber: 7,
		source: 'minna no nihongo',
		level: Level.N5,
	},
	{
		id: 'lesson-002',
		lessonNumber: 8,
		source: 'minna no nihongo',
		level: Level.N5,
	},
	{
		id: 'lesson-001',
		lessonNumber: 9,
		source: 'minna no nihongo',
		level: Level.N5,
	},
	{
		id: 'lesson-002',
		lessonNumber: 10,
		source: 'minna no nihongo',
		level: Level.N5,
	},
	{
		id: 'lesson-003',
		lessonNumber: 15,
		source: 'soumatome',
		level: Level.N3,
	},
];

// ============================================
// KANJI DATA (with examples nested)
// ============================================
export const kanjis: Kanji[] = [
	{
		id: 'kanji-001',
		character: '食',
		onyomi: 'ショク、ジキ',
		kunyomi: 'た.べる、く.う',
		meaning: 'ăn, thức ăn',
		level: Level.N5,
		strokeCount: 9,
		lessonId: 'lesson-001',
		exampleId: ['example-002', 'example-005', 'example-014'],
	},
	{
		id: 'kanji-002',
		character: '飲',
		onyomi: 'イン、オン',
		kunyomi: 'の.む',
		meaning: 'uống',
		level: Level.N5,
		strokeCount: 12,
		lessonId: 'lesson-001',
		exampleId: ['example-003', 'example-015'],
	},
	{
		id: 'kanji-003',
		character: '勉',
		onyomi: 'ベン',
		kunyomi: 'つと.める',
		meaning: 'học tập, cố gắng',
		level: Level.N4,
		strokeCount: 10,
		lessonId: 'lesson-003',
		exampleId: ['example-016'],
	},
];

// ============================================
// VOCABULARY DATA (with examples nested)
// ============================================
export const MOCK_VOCABULARIES: Vocabulary[] = [
	{
		id: 'vocab-001',
		word: 'たべます',
		kanjiId: ['kanji-001'],
		romaji: 'tabemasu',
		meaning: 'ăn',
		wordType: WordType.VERB,
		level: Level.N5,
		lessonId: 'lesson-001',
		examples: [],
		mediaId: ['media-001'],
		createdAt: '',
		updatedAt: '',
	},
	{
		id: 'vocab-002',
		word: 'のみます',
		kanjiId: ['kanji-002'],
		romaji: 'nomimasu',
		meaning: 'uống',
		wordType: WordType.VERB,
		level: Level.N5,
		lessonId: 'lesson-001',
		examples: [{ id: '', title: '', description: '' }],
		mediaId: ['media-002'],
		createdAt: '',
		updatedAt: '',
	},
	{
		id: 'vocab-003',
		word: 'がっこう',
		kanjiId: [],
		romaji: 'gakkou',
		meaning: 'trường học',
		wordType: WordType.NOUN,
		level: Level.N5,
		lessonId: 'lesson-001',
		examples: [{ id: '', title: '', description: '' }],
		mediaId: ['media-003'],
		createdAt: '',
		updatedAt: '',
	},
	{
		id: 'vocab-004',
		word: 'きれい',
		kanjiId: [],
		romaji: 'kirei',
		meaning: 'đẹp, sạch sẽ',
		wordType: WordType.ADJECTIVE,
		level: Level.N5,
		lessonId: 'lesson-002',
		examples: [{ id: '', title: '', description: '' }],
		mediaId: [],
		createdAt: '',
		updatedAt: '',
	},
	{
		id: '3f0e5b7a-1a3e-4c9a-9e32-0dbe6c7b1f01',
		word: '食べる',
		kanjiId: [],
		romaji: 'taberu',
		meaning: 'ăn',
		wordType: WordType.VERB,
		level: Level.N5,
		examples: [{ id: '', title: '', description: '' }],
		mediaId: [],
		createdAt: '',
		updatedAt: '',
	},
	{
		id: 'b1a2e8c4-6c77-4f2b-9c65-2c71d5e7b902',
		word: '行く',
		kanjiId: [],
		romaji: 'iku',
		meaning: 'đi',
		wordType: WordType.VERB,
		level: Level.N5,
		examples: [{ id: '', title: '', description: '' }],
		mediaId: [],
		createdAt: '',
		updatedAt: '',
	},
	{
		id: 'c7d0e3a9-4f9c-41b1-b6a0-0a8e0e93b203',
		word: '見る',
		kanjiId: [],
		romaji: 'miru',
		meaning: 'xem, nhìn',
		wordType: WordType.VERB,
		level: Level.N5,
		examples: [{ id: '', title: '', description: '' }],
		mediaId: [],
		createdAt: '',
		updatedAt: '',
	},
	{
		id: 'e41d7a20-ecf3-4c92-9b0f-77c02cde9404',
		word: '大きい',
		kanjiId: [],
		romaji: 'ookii',
		meaning: 'to, lớn',
		wordType: WordType.ADJECTIVE,
		level: Level.N5,
		examples: [{ id: '', title: '', description: '' }],
		mediaId: [],
		createdAt: '',
		updatedAt: '',
	},
	{
		id: '9a5c1f4e-8c19-4d68-bde4-1c7cdb1d3a05',
		word: '小さい',
		kanjiId: [],
		romaji: 'chiisai',
		meaning: 'nhỏ',
		wordType: WordType.ADJECTIVE,
		level: Level.N5,
		examples: [{ id: '', title: '', description: '' }],
		mediaId: [],
		createdAt: '',
		updatedAt: '',
	},
	{
		id: '2d7f9a40-bb16-4fa2-8f64-7f63b9b9ad06',
		word: '学生',
		kanjiId: [],
		romaji: 'gakusei',
		meaning: 'học sinh, sinh viên',
		wordType: WordType.NOUN,
		level: Level.N5,
		examples: [{ id: '', title: '', description: '' }],
		mediaId: [],
		createdAt: '',
		updatedAt: '',
	},
	{
		id: '6e8b9c21-6c0f-4bb7-a87d-1f7f6d1b8e07',
		word: '先生',
		kanjiId: [],
		romaji: 'sensei',
		meaning: 'giáo viên',
		wordType: WordType.NOUN,
		level: Level.N5,
		examples: [{ id: '', title: '', description: '' }],
		mediaId: [],
		createdAt: '',
		updatedAt: '',
	},
	{
		id: '0b2dfd31-8a52-4c73-8f03-4a4f45c9b108',
		word: '本',
		kanjiId: [],
		romaji: 'hon',
		meaning: 'sách',
		wordType: WordType.NOUN,
		level: Level.N5,
		examples: [{ id: '', title: '', description: '' }],
		mediaId: [],
		createdAt: '',
		updatedAt: '',
	},
	{
		id: 'e3d9c7f1-2f47-4c27-b5a3-17c6c5a21e09',
		word: '買う',
		kanjiId: [],
		romaji: 'kau',
		meaning: 'mua',
		wordType: WordType.VERB,
		level: Level.N5,
		examples: [{ id: '', title: '', description: '' }],
		mediaId: [],
		createdAt: '',
		updatedAt: '',
	},
	{
		id: '4a12b62b-0a25-45e7-a47c-f6f7d61c5f10',
		word: '飲む',
		kanjiId: [],
		romaji: 'nomu',
		meaning: 'uống',
		wordType: WordType.VERB,
		level: Level.N5,
		examples: [{ id: '', title: '', description: '' }],
		mediaId: [],
		createdAt: '',
		updatedAt: '',
	},

	// ---- N4 ----
	{
		id: '8c3e8d55-bc7b-4f58-9c1a-8b65aab1e111',
		word: '始める',
		kanjiId: [],
		romaji: 'hajimeru',
		meaning: 'bắt đầu',
		wordType: WordType.VERB,
		level: Level.N4,
		examples: [{ id: '', title: '', description: '' }],
		mediaId: [],
		createdAt: '',
		updatedAt: '',
	},
	{
		id: 'c90a0b39-9df6-40f3-bd2f-23b3a1f2e212',
		word: '終わる',
		kanjiId: [],
		romaji: 'owaru',
		meaning: 'kết thúc',
		wordType: WordType.VERB,
		level: Level.N4,
		examples: [{ id: '', title: '', description: '' }],
		mediaId: [],
		createdAt: '',
		updatedAt: '',
	},
	{
		id: 'b8b9c112-f1f3-4b0c-9a2b-6cb8c6c1f313',
		word: '便利',
		kanjiId: [],
		romaji: 'benri',
		meaning: 'tiện lợi',
		wordType: WordType.ADJECTIVE,
		level: Level.N4,
		examples: [{ id: '', title: '', description: '' }],
		mediaId: [],
		createdAt: '',
		updatedAt: '',
	},
	{
		id: 'c2c4d9b5-6f59-4f9e-93f7-4f9b8a91a414',
		word: '必要',
		kanjiId: [],
		romaji: 'hitsuyou',
		meaning: 'cần thiết',
		wordType: WordType.ADJECTIVE,
		level: Level.N4,
		examples: [{ id: '', title: '', description: '' }],
		mediaId: [],
		createdAt: '',
		updatedAt: '',
	},
	{
		id: '1a91c9f1-7a77-4db1-9a0b-fb2e4f9c1515',
		word: '会社',
		kanjiId: [],
		romaji: 'kaisha',
		meaning: 'công ty',
		wordType: WordType.NOUN,
		level: Level.N4,
		examples: [{ id: '', title: '', description: '' }],
		mediaId: [],
		createdAt: '',
		updatedAt: '',
	},
];

// ============================================
// GRAMMAR DATA (with examples nested)
// ============================================
export const grammars: Grammar[] = [
	{
		id: 'grammar-001',
		pattern: '〜は〜です',
		structure: '[Noun] は [Noun/Na-adjective] です',
		meaning: '~ là ~',
		explaination:
			"Dùng để giới thiệu hoặc mô tả một sự vật, sự việc. 'は' đánh dấu chủ đề của câu, 'です' là trợ động từ thể lịch sự.",
		notes: 'Phủ định: 〜ではありません / 〜じゃありません',
		level: Level.N5,
		lessonId: 'lesson-001',
		exampleId: ['example-001', 'example-010', 'example-011'],
	},
	{
		id: 'grammar-002',
		pattern: '〜を〜ます',
		structure: '[Noun (object)] を [Verb] ます',
		meaning: 'Làm gì với cái gì',
		explaination:
			'を đánh dấu tân ngữ trực tiếp của động từ. Chỉ hành động tác động trực tiếp lên đối tượng nào đó.',
		notes: 'を chỉ đi với động từ tha động (transitive verb)',
		level: Level.N5,
		lessonId: 'lesson-001',
		exampleId: ['example-002', 'example-003', 'example-012'],
	},
	{
		id: 'grammar-003',
		pattern: '〜が好きです',
		structure: '[Noun] が好きです / 好きではありません',
		meaning: 'thích ~',
		explaination:
			'Dùng để diễn tả sự yêu thích đối với một sự vật, hiện tượng. が đánh dấu đối tượng được yêu thích.',
		notes: 'Có thể thêm とても (rất), あまり (không lắm) để diễn tả mức độ',
		level: Level.N5,
		lessonId: 'lesson-002',
		exampleId: ['example-004', 'example-013'],
	},
	{
		id: 'g-0001',
		pattern: '～です',
		structure: 'N は N です',
		meaning: 'là',
		explaination: 'Dùng để khẳng định',
		notes: 'Cấu trúc cơ bản nhất',
		level: Level.N5,
		lessonId: 'lesson-002',
		exampleId: [],
	},
	{
		id: 'g-0002',
		pattern: '～ではありません',
		structure: 'N は N ではありません',
		meaning: 'không phải là',
		explaination: '',
		notes: 'Dạng phủ định của です',
		level: Level.N5,
		lessonId: 'lesson-003',
		exampleId: [],
	},
	{
		id: 'g-0003',
		pattern: '～か',
		structure: 'N は N ですか',
		meaning: 'câu hỏi yes/no',
		notes: 'Dùng để hỏi',
		level: Level.N5,
		lessonId: 'lesson-004',
		exampleId: [],
	},
	{
		id: 'g-0004',
		pattern: 'これ／それ／あれ',
		structure: 'これ は N です',
		meaning: 'đại từ chỉ vật',
		notes: 'Phân biệt khoảng cách',
		level: Level.N5,
		lessonId: 'lesson-004',
		exampleId: [],
	},
	{
		id: 'g-0005',
		pattern: '～の',
		structure: 'N の N',
		meaning: 'sở hữu',
		notes: 'Diễn tả quan hệ',
		level: Level.N5,
		lessonId: 'lesson-005',
		exampleId: [],
	},
	{
		id: 'g-0006',
		pattern: '～ます',
		structure: 'V-ます',
		meaning: 'dạng lịch sự',
		notes: 'Thì hiện tại / tương lai',
		level: Level.N5,
		lessonId: 'lesson-005',
		exampleId: [],
	},
	{
		id: 'g-0007',
		pattern: '～ません',
		structure: 'V-ません',
		meaning: 'phủ định',
		notes: 'Phủ định của ～ます',
		level: Level.N5,
		lessonId: 'lesson-006',
		exampleId: [],
	},
	{
		id: 'g-0008',
		pattern: '～を',
		structure: 'N を V',
		meaning: 'trợ từ tân ngữ',
		notes: 'Chỉ đối tượng tác động',
		level: Level.N5,
		lessonId: 'lesson-006',
		exampleId: [],
	},
	{
		id: 'g-0009',
		pattern: '～に／へ',
		structure: 'N に／へ 行きます',
		meaning: 'chỉ điểm đến',
		notes: 'Dùng với động từ di chuyển',
		level: Level.N5,
		lessonId: 'lesson-007',
		exampleId: [],
	},
	{
		id: 'g-0010',
		pattern: '～で',
		structure: 'N で V',
		meaning: 'địa điểm xảy ra hành động',
		notes: 'Không dùng cho tồn tại',
		level: Level.N5,
		lessonId: 'lesson-007',
		exampleId: [],
	},
	{
		id: 'g-0011',
		pattern: '～と思います',
		structure: '普通形 + と思います',
		meaning: 'tôi nghĩ rằng',
		notes: 'Diễn đạt ý kiến',
		level: Level.N4,
		lessonId: 'lesson-008',
		exampleId: [],
	},
	{
		id: 'g-0012',
		pattern: '～そうです',
		structure: '普通形 + そうです',
		meaning: 'nghe nói là',
		notes: 'Truyền đạt thông tin',
		level: Level.N4,
		lessonId: 'lesson-008',
		exampleId: [],
	},
];

// ============================================
// EXAMPLE DATA
// ============================================
export const examples: Example[] = [
	{
		id: 'example-001',
		japanese: 'わたしは学生です。',
		romaji: 'Tôi là sinh viên.',
		vietnamese: '',
		explanation: 'grammar-001',
	},
	{
		id: 'example-002',
		japanese: 'ごはんを食べます。',
		romaji: 'Tôi ăn cơm.',
		vietnamese: 'vocab-001',
		explanation: '',
	},
	{
		id: 'example-003',
		japanese: '水を飲みます。',
		romaji: 'Tôi uống nước.',
		vietnamese: 'vocab-002',
		explanation: '',
	},
	{
		id: 'example-004',
		japanese: 'わたしは音楽が好きです。',
		romaji: 'Tôi thích âm nhạc.',
		vietnamese: '',
		explanation: '',
	},
	{
		id: 'example-005',
		japanese: '食事の時間です。',
		romaji: 'Đến giờ ăn rồi.',
		vietnamese: '',
		explanation: '',
	},
	{
		id: 'example-006',
		japanese: 'わたしは学生です。',
		romaji: 'Watashi wa gakusei desu.',
		vietnamese: 'Tôi là sinh viên.',
		explanation: 'Sử dụng です để khẳng định nghề nghiệp',
	},
	{
		id: 'example-007',
		japanese: 'これは本です。',
		romaji: 'Kore wa hon desu.',
		vietnamese: 'Đây là quyển sách.',
		explanation: 'Sử dụng です để xác định đồ vật',
	},
	{
		id: 'example-008',
		japanese: '田中さんは先生です。',
		romaji: 'Tanaka-san wa sensei desu.',
		vietnamese: 'Anh/Chị Tanaka là giáo viên.',
		explanation: 'Giới thiệu nghề nghiệp của người khác',
	},
	{
		id: 'example-002',
		japanese: 'ごはんを食べます。',
		romaji: '',
		vietnamese: 'Tôi ăn cơm.',
		explanation: '',
	},
	{
		id: 'example-006',
		japanese: '朝ごはんを食べました。',
		romaji: '',
		vietnamese: 'Tôi đã ăn sáng.',
		explanation: '',
	},
	{
		id: 'example-008',
		japanese: '学校へ行きます。',
		romaji: '',
		vietnamese: '',
		explanation: 'Tôi đi học.',
	},
	{
		id: 'example-011',
		japanese: 'きれいな花です。',
		romaji: '',
		vietnamese: 'Đây là hoa đẹp.',
		explanation: '',
	},
	{
		id: 'example-056',
		japanese: '水を飲みます。',
		romaji: '',
		vietnamese: 'Tôi uống nước.',
		explanation: '',
	},
	{
		id: 'example-027',
		japanese: 'コーヒーを飲みました。',
		romaji: '',
		vietnamese: 'Tôi đã uống cà phê.',
		explanation: '',
	},
	{
		id: 'ex-100',
		japanese: 'ご飯を食べます。',
		romaji: 'gohan o tabemasu.',
		vietnamese: 'Tôi ăn cơm.',
		explanation: 'Câu ví dụ sử dụng động từ 食べる ở dạng lịch sự.',
	},
	{
		id: 'ex-123',
		japanese: '学校へ行きます。',
		romaji: 'gakkou e ikimasu.',
		vietnamese: 'Tôi đi đến trường.',
		explanation: 'Dùng 行く để diễn tả sự di chuyển đến một địa điểm.',
	},
	{
		id: 'ex-393',
		japanese: 'テレビを見ます。',
		romaji: 'terebi o mimasu.',
		vietnamese: 'Tôi xem TV.',
		explanation: '見る được dùng cho hành động xem, nhìn.',
	},
	{
		id: 'ex-194',
		japanese: '会社で働きます。',
		romaji: 'kaisha de hatarakimasu.',
		vietnamese: 'Tôi làm việc ở công ty.',
		explanation: 'で chỉ địa điểm diễn ra hành động.',
	},
	{
		id: 'ex-145',
		japanese: 'お金が必要です。',
		romaji: 'okane ga hitsuyou desu.',
		vietnamese: 'Tôi cần tiền.',
		explanation: '必要 là tính từ な, thường dùng với が.',
	},
	{
		id: 'ex-131',
		japanese: 'このアプリは便利です。',
		romaji: 'kono apuri wa benri desu.',
		vietnamese: 'Ứng dụng này rất tiện.',
		explanation: '便利 là tính từ な.',
	},
	{
		id: 'ex-1900',
		japanese: '授業が終わります。',
		romaji: 'jugyou ga owarimasu.',
		vietnamese: 'Buổi học kết thúc.',
		explanation: '終わる dùng cho sự kết thúc.',
	},
	{
		id: 'ex-998',
		japanese: '仕事を始めます。',
		romaji: 'shigoto o hajimemasu.',
		vietnamese: 'Tôi bắt đầu công việc.',
		explanation: '始める diễn tả sự bắt đầu hành động.',
	},
	{
		id: 'ex-340',
		japanese: '大きい家です。',
		romaji: 'ookii ie desu.',
		vietnamese: 'Đó là ngôi nhà lớn.',
		explanation: 'Tính từ い dùng để miêu tả kích thước.',
	},
	{
		id: 'ex-778',
		japanese: '水を飲みます。',
		romaji: 'mizu o nomimasu.',
		vietnamese: 'Tôi uống nước.',
		explanation: '飲む dùng cho đồ uống.',
	},
	{
		id: 'ex-199',
		japanese: 'パンを買います。',
		romaji: 'pan o kaimasu.',
		vietnamese: 'Tôi mua bánh mì.',
		explanation: 'Động từ 買う dùng cho hành động mua.',
	},
	{
		id: 'ex-556',
		japanese: '本を読みます。',
		romaji: 'hon o yomimasu.',
		vietnamese: 'Tôi đọc sách.',
		explanation: '本 là danh từ chỉ đồ vật.',
	},
	{
		id: 'ex-667',
		japanese: '先生に聞きます。',
		romaji: 'sensei ni kikimasu.',
		vietnamese: 'Tôi hỏi giáo viên.',
		explanation: 'Dùng trợ từ に để chỉ đối tượng được hỏi.',
	},
	{
		id: 'ex-331',
		japanese: '私は学生です。',
		romaji: 'watashi wa gakusei desu.',
		vietnamese: 'Tôi là sinh viên.',
		explanation: 'Mẫu câu danh từ + です.',
	},
	{
		id: 'ex-566',
		japanese: '小さい猫です。',
		romaji: 'chiisai neko desu.',
		vietnamese: 'Đó là con mèo nhỏ.',
		explanation: '小さい là tính từ trái nghĩa với 大きい.',
	},
];

// ============================================
// MEDIA DATA
// ============================================
export const medias = [
	{
		id: 'media-001',
		audio: '/audio/tabemasu.mp3',
		image: '/images/eating.jpg',
		vocabularyId: 'vocab-001',
		createdAt: new Date('2024-01-01'),
		updatedAt: new Date('2024-01-01'),
	},
	{
		id: 'media-002',
		audio: '/audio/nomimasu.mp3',
		image: '/images/drinking.jpg',
		vocabularyId: 'vocab-002',
		createdAt: new Date('2024-01-01'),
		updatedAt: new Date('2024-01-01'),
	},
	{
		id: 'media-003',
		audio: '/audio/gakkou.mp3',
		image: '/images/school.jpg',
		vocabularyId: 'vocab-003',
		createdAt: new Date('2024-01-01'),
		updatedAt: new Date('2024-01-01'),
	},
];

// ============================================
// LISTENING DATA
// ============================================
const listenings = [
	{
		id: 'listening-001',
		level: 'N5',
	},
	{
		id: 'listening-002',
		level: 'N4',
	},
];

// ============================================
// READING DATA
// ============================================
const readings = [
	{
		id: 'reading-001',
		level: 'N5',
	},
	{
		id: 'reading-002',
		level: 'N4',
	},
];
